In [37]:
import numpy as np

In [38]:
np.array([3,4.,6.,5])

array([3., 4., 6., 5.])

In [39]:
np.zeros((5,6), dtype="float")

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [40]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [42]:
np.random.random((3,3))

array([[0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 ],
       [0.6235101 , 0.33800761, 0.67475232]])

In [43]:
np.random.normal(0,1,(3,3))

array([[ 1.0657892 , -0.69993739,  0.14407911],
       [ 0.3985421 ,  0.02686925,  1.05583713],
       [-0.07318342, -0.66572066, -0.04411241]])

In [44]:
np.random.randint(0,10,(3,3))

array([[7, 2, 9],
       [2, 3, 3],
       [2, 3, 4]])

In [45]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array

In [46]:
print(x1)

[5 0 3 3 7 9]


In [47]:
np.random.seed(0) # seed for reproducibility
x2 = np.random.randint(10, size=6) #it's same ((np.random.randint((0,10), size=6))) # One-dimensional array
x1 = np.random.randint(10, size=(3,4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3,4,5))

In [48]:
print("x1 ndim: ",x1.ndim)
print("x1 shape: ",x1.shape)
print("x1 size: ",x1.size)

x1 ndim:  2
x1 shape:  (3, 4)
x1 size:  12


In [49]:
import numpy as np # linear algebra
import pandas as pd

In [50]:
labels = ['w','x','y','z']
list = [10,20,30,40]
array = np.array([10,20,30,40])
dict = {'w':10,'x':20,'y':30,'z':40}

In [51]:
pd.Series(list,labels)

w    10
x    20
y    30
z    40
dtype: int64

In [53]:
ksr = pd.Series([1,2,3,4], index = ['ksr', 'kk', 'ss', 'ks'])
ksr


ksr    1
kk     2
ss     3
ks     4
dtype: int64

In [59]:
from numpy.random import randn
np.random.seed()
dataframe = pd.DataFrame(randn(10,5),index='A B C D E F G H I J'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
dataframe

Score1    Score2    Score3    Score4    Score5
A  0.840699 -0.200170  0.965308 -1.687486  0.440869
B  1.052455  1.187849  1.512361  1.472685 -0.130706
C  0.686234  1.162095  0.750961  0.140925  1.260154
D -0.419049  0.058463  0.641041 -0.059067 -0.243727
E  0.709777 -0.817083  1.133204 -0.229155  1.204770
F  0.328902  1.336996 -1.536820  1.439838 -0.772119
G -0.405545  1.239622 -0.539628 -0.978750 -0.046162
H  0.964231 -2.031483 -1.491860 -0.193977 -0.792566
I  0.544931 -0.348491 -0.678726 -0.634057  0.840169
J -0.180772 -0.011184  0.527014  2.169298 -1.250683

In [71]:
from numpy.random import randn
np.random.seed(0)
df = pd.DataFrame(randn(5,5),index='A B C D E' .split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df

Score1    Score2    Score3    Score4    Score5
A  1.764052  0.400157  0.978738  2.240893  1.867558
B -0.977278  0.950088 -0.151357 -0.103219  0.410599
C  0.144044  1.454274  0.761038  0.121675  0.443863
D  0.333674  1.494079 -0.205158  0.313068 -0.854096
E -2.552990  0.653619  0.864436 -0.742165  2.269755

In [74]:
from numpy.random import randn
np.random.seed(1)
df = pd.DataFrame(randn(12,5),index='A B C D E F G H I J K L' .split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df

Score1    Score2    Score3    Score4    Score5
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408
B -2.301539  1.744812 -0.761207  0.319039 -0.249370
C  1.462108 -2.060141 -0.322417 -0.384054  1.133769
D -1.099891 -0.172428 -0.877858  0.042214  0.582815
E -1.100619  1.144724  0.901591  0.502494  0.900856
F -0.683728 -0.122890 -0.935769 -0.267888  0.530355
G -0.691661 -0.396754 -0.687173 -0.845206 -0.671246
H -0.012665 -1.117310  0.234416  1.659802  0.742044
I -0.191836 -0.887629 -0.747158  1.692455  0.050808
J -0.636996  0.190915  2.100255  0.120159  0.617203
K  0.300170 -0.352250 -1.142518 -0.349343 -0.208894
L  0.586623  0.838983  0.931102  0.285587  0.885141

In [77]:
df[['Score3', 'Score4']]

Score3    Score4
A -0.528172 -1.072969
B -0.761207  0.319039
C -0.322417 -0.384054
D -0.877858  0.042214
E  0.901591  0.502494
F -0.935769 -0.267888
G -0.687173 -0.845206
H  0.234416  1.659802
I -0.747158  1.692455
J  2.100255  0.120159
K -1.142518 -0.349343
L  0.931102  0.285587

In [79]:
df['Score6'] = df['Score1'] +df['Score2']
df

Score1    Score2    Score3    Score4    Score5    Score6
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408  1.012589
B -2.301539  1.744812 -0.761207  0.319039 -0.249370 -0.556727
C  1.462108 -2.060141 -0.322417 -0.384054  1.133769 -0.598033
D -1.099891 -0.172428 -0.877858  0.042214  0.582815 -1.272319
E -1.100619  1.144724  0.901591  0.502494  0.900856  0.044105
F -0.683728 -0.122890 -0.935769 -0.267888  0.530355 -0.806618
G -0.691661 -0.396754 -0.687173 -0.845206 -0.671246 -1.088414
H -0.012665 -1.117310  0.234416  1.659802  0.742044 -1.129975
I -0.191836 -0.887629 -0.747158  1.692455  0.050808 -1.079465
J -0.636996  0.190915  2.100255  0.120159  0.617203 -0.446080
K  0.300170 -0.352250 -1.142518 -0.349343 -0.208894 -0.052080
L  0.586623  0.838983  0.931102  0.285587  0.885141  1.425607

In [89]:
df.drop('Score6',axis=1)
df

Score1    Score2    Score3    Score4    Score5    Score6
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408  1.012589
B -2.301539  1.744812 -0.761207  0.319039 -0.249370 -0.556727
C  1.462108 -2.060141 -0.322417 -0.384054  1.133769 -0.598033
D -1.099891 -0.172428 -0.877858  0.042214  0.582815 -1.272319
E -1.100619  1.144724  0.901591  0.502494  0.900856  0.044105
F -0.683728 -0.122890 -0.935769 -0.267888  0.530355 -0.806618
G -0.691661 -0.396754 -0.687173 -0.845206 -0.671246 -1.088414
H -0.012665 -1.117310  0.234416  1.659802  0.742044 -1.129975
I -0.191836 -0.887629 -0.747158  1.692455  0.050808 -1.079465
J -0.636996  0.190915  2.100255  0.120159  0.617203 -0.446080
K  0.300170 -0.352250 -1.142518 -0.349343 -0.208894 -0.052080
L  0.586623  0.838983  0.931102  0.285587  0.885141  1.425607

In [90]:
df.loc['L']

Score1    0.586623
Score2    0.838983
Score3    0.931102
Score4    0.285587
Score5    0.885141
Score6    1.425607
Name: L, dtype: float64

In [93]:
df.iloc[1]

Score1   -2.301539
Score2    1.744812
Score3   -0.761207
Score4    0.319039
Score5   -0.249370
Score6   -0.556727
Name: B, dtype: float64

In [97]:
df[df>0.5]

Score1    Score2    Score3    Score4    Score5    Score6
A  1.624345       NaN       NaN       NaN  0.865408  1.012589
B       NaN  1.744812       NaN       NaN       NaN       NaN
C  1.462108       NaN       NaN       NaN  1.133769       NaN
D       NaN       NaN       NaN       NaN  0.582815       NaN
E       NaN  1.144724  0.901591  0.502494  0.900856       NaN
F       NaN       NaN       NaN       NaN  0.530355       NaN
G       NaN       NaN       NaN       NaN       NaN       NaN
H       NaN       NaN       NaN  1.659802  0.742044       NaN
I       NaN       NaN       NaN  1.692455       NaN       NaN
J       NaN       NaN  2.100255       NaN  0.617203       NaN
K       NaN       NaN       NaN       NaN       NaN       NaN
L  0.586623  0.838983  0.931102       NaN  0.885141  1.425607

In [106]:
df = pd.DataFrame({'Cricket':[1,1,np.nan,4,6,7,1,np.nan],
                  'Baseball':[5,np.nan,np.nan,5,7,2,4,5],
                  'Tennis':[1,2,3,4,5,6,7,8]})
df

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      1.0       NaN       2
2      NaN       NaN       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       2.0       6
6      1.0       4.0       7
7      NaN       5.0       8

In [107]:
df.dropna()

Cricket  Baseball  Tennis
0      1.0       5.0       1
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       2.0       6
6      1.0       4.0       7

In [108]:
df.fillna(value=0)

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      1.0       0.0       2
2      0.0       0.0       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       2.0       6
6      1.0       4.0       7
7      0.0       5.0       8

In [110]:
CustID_grouped = df.groupby("Cricket")
CustID_grouped.mean()

Baseball    Tennis
Cricket                    
1.0           4.5  3.333333
4.0           5.0  4.000000
6.0           7.0  5.000000
7.0           2.0  6.000000

In [103]:
dat = {'CustID':['1001','1001','1002','1002','1003','1003'],
       'CustName':['UIPat','DatRob','Goog','Chrysler','Ford','GM'],
       'Profitinlakhs':[2005,3245,1245,8765,5463,3547]}
df = pd.DataFrame(dat)
df

CustID  CustName  Profitinlakhs
0   1001     UIPat           2005
1   1001    DatRob           3245
2   1002      Goog           1245
3   1002  Chrysler           8765
4   1003      Ford           5463
5   1003        GM           3547

In [104]:
CustID_grouped = df.groupby("CustID")

In [105]:
CustID_grouped.mean()

Profitinlakhs
CustID               
1001             2625
1002             5005
1003             4505

In [112]:
dafa1 = pd.DataFrame({'CustID': ['101', '102', '103', '104'],
                        'Sales': [13456, 45321, 54385, 53212],
                        'Priority': ['CAT0', 'CAT1', 'CAT2', 'CAT3'],
                        'Prime': ['yes', 'no', 'no', 'yes']},
                        index=[0, 1, 2, 3])

dafa2 = pd.DataFrame({'CustID': ['101', '103', '104', '105'],
                        'Sales': [13456, 54385, 53212, 4534],
                        'Payback': ['CAT4', 'CAT5', 'CAT6', 'CAT7'],
                        'Imp': ['yes', 'no', 'no', 'no']},
                         index=[4, 5, 6, 7])

dafa3 = pd.DataFrame({'CustID': ['101', '104', '105', '106'],
                        'Sales': [13456, 53212, 4534, 3241],
                        'Pol': ['CAT8', 'CAT9', 'CAT10', 'CAT11'],
                        'Level': ['yes', 'no', 'no', 'yes']},
                        index=[8, 9, 10, 11])


In [116]:
pd.concat([dafa1, dafa2, dafa3], axis =1)

CustID    Sales Priority Prime CustID    Sales Payback  Imp CustID  \
0     101  13456.0     CAT0   yes    NaN      NaN     NaN  NaN    NaN   
1     102  45321.0     CAT1    no    NaN      NaN     NaN  NaN    NaN   
2     103  54385.0     CAT2    no    NaN      NaN     NaN  NaN    NaN   
3     104  53212.0     CAT3   yes    NaN      NaN     NaN  NaN    NaN   
4     NaN      NaN      NaN   NaN    101  13456.0    CAT4  yes    NaN   
5     NaN      NaN      NaN   NaN    103  54385.0    CAT5   no    NaN   
6     NaN      NaN      NaN   NaN    104  53212.0    CAT6   no    NaN   
7     NaN      NaN      NaN   NaN    105   4534.0    CAT7   no    NaN   
8     NaN      NaN      NaN   NaN    NaN      NaN     NaN  NaN    101   
9     NaN      NaN      NaN   NaN    NaN      NaN     NaN  NaN    104   
10    NaN      NaN      NaN   NaN    NaN      NaN     NaN  NaN    105   
11    NaN      NaN      NaN   NaN    NaN      NaN     NaN  NaN    106   

      Sales    Pol Level  
0       NaN    NaN   NaN  
1       NaN    NaN   NaN  
2       NaN    NaN   NaN  
3       NaN    NaN   NaN  
4       NaN    NaN   NaN  
5       NaN    NaN   NaN  
6       NaN    NaN   NaN  
7       NaN    NaN   NaN  
8   13456.0   CAT8   yes  
9   53212.0   CAT9    no  
10   4534.0  CAT10    no  
11   3241.0  CAT11   yes